(*****************************************************************************
 *                                                                           *
 *  This file is part of the UMLCat Component Library.                       *
 *                                                                           *
 *  See the file COPYING.modifiedLGPL.txt, included in this distribution,    *
 *  for details about the copyright.                                         *
 *                                                                           *
 *  This program is distributed in the hope that it will be useful,          *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of           *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                     *
 *                                                                           *
 *****************************************************************************
 **)

(* "sxmlpad_language.inc" *)

{.define sxmlpad_language_english}
{.define sxmlpad_language_spanisheurope}
{$define sxmlpad_language_spanishlatam}
{.define sxmlpad_language_french}
{.define sxmlpad_language_german}
{.define sxmlpad_language_portuguese}
